# A version of IAST that supports hrasva e and o.
[vowels]
"अ" = "a"
"आ" = "ā"
"इ" = "i"
"ई" = "ī"
"उ" = "u"
"ऊ" = "ū"
"ऋ" = "ṛ"
"ॠ" = "ṝ"
"ऌ" = "ḷ"
"ॡ" = "ḹ"
"ऎ" = "e"
"ए" = "ē"
"ऐ" = "ai"
"ऒ" = "o"
"ओ" = "ō"
"औ" = "au"

[yogavaahas]
"ं" = "ṃ"
"ः" = "ḥ"
"ँ" = "~"

[virama]
"्" = ""

[accents]
"॑" = "̭"
"॒" = "॒"
"᳡" = "̀"
"꣡" = "́"
"꣢" = "²"
"꣣" = "³"
"꣤" = "⁴"
"꣥" = "⁵"
"꣦" = "⁶"
"꣧" = "⁷"
"꣨" = "⁸"
"꣩" = "⁹"
"꣪" = "꣪"
"꣫" = "꣫"
"꣬" = "꣬"
"꣭" = "꣭"
"꣮" = "꣮"
"꣯" = "꣯"
"꣰" = "꣰"
"꣱" = "꣱"

[consonants]
"क" = "k"
"ख" = "kh"
"ग" = "g"
"घ" = "gh"
"ङ" = "ṅ"
"च" = "c"
"छ" = "ch"
"ज" = "j"
"झ" = "jh"
"ञ" = "ñ"
"ट" = "ṭ"
"ठ" = "ṭh"
"ड" = "ḍ"
"ढ" = "ḍh"
"ण" = "ṇ"
"त" = "t"
"थ" = "th"
"द" = "d"
"ध" = "dh"
"न" = "n"
"प" = "p"
"फ" = "ph"
"ब" = "b"
"भ" = "bh"
"म" = "m"
"य" = "y"
"र" = "r"
"ल" = "l"
"व" = "v"
"श" = "ś"
"ष" = "ṣ"
"स" = "s"
"ह" = "h"
"ळ" = "ḻ"
"क्ष" = "kṣ"
"ज्ञ" = "jñ"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "ōṃ"
"ऽ" = "'"
"।" = "|"
"॥" = "||"

[extra_consonants]
"क़" = "q"
"ख़" = "k͟h"
"ग़" = "ġ"
"ज़" = "z"
"ड़" = "r̤"
"ढ़" = "r̤h"
"फ़" = "f"
"य़" = "ẏ"
"ऱ" = "ṟ"
"ऴ" = "l̤"
"ऩ" = "ṉ"

[alternates]
"|" = [ ".", "/",]
"||" = [ "..", "//",]
"'" = [ "`",]
"m̐" = [ "ṁ",]
"ṃ" = ["ṃ"]
"ḥ" = ["ḥ"]
"ṭ" = ["ṭ"]
"ṭh" = ["ṭh"]
"ḍ" = ["ḍ"]
"ḍh" = ["ḍh"]
"ṇ" = ["ṇ"]
"ṅ" = ["ṅ"]
"ñ" = ["ñ"]
"ṣ" = ["ṣ"]
"ṛ" = [ "r̥", "ṛ"]
"ṝ" = [ "ṝ", "r̥̄", "r̥̄", "ṝ", "ṝ",]
"́" = [ "¹",]

[accented_vowel_alternates]
"á" = [ "á",]
"é" = [ "é",]
"í" = [ "í",]
"aí" = [ "aí",]
"ó" = [ "ó",]
"ú" = [ "ú",]
"aú" = [ "aú",]
"à" = [ "à",]
"è" = [ "è",]
"ì" = [ "ì",]
"aì" = [ "aì",]
"ò" = [ "ò",]
"ù" = [ "ù",]
"aù" = [ "aù",]
"ṛ̀" = [ "r̥̀", "ṛ̀"]
